# Disable sudo to speed up build
sudo: false

# Set build language to Python
language: python

# Set python version
python: 3.7.5

# Setting up Isolated vitrualenvs

# virtualenv:
#   system_site_packages: true

install:
  - pip install pipenv pytest
  - pipenv --python 3
  - pipenv install

# Run tests
# script:
#   - pytest

# Submit coverage
after_success:
  - codecov
