"""empty message

Revision ID: 5beeef835e22
Revises: 834f110b58ca
Create Date: 2019-11-29 11:46:52.999121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beeef835e22'
down_revision = '834f110b58ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('postcode', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'results', ['game_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='unique')
    op.drop_column('players', 'postcode')
    # ### end Alembic commands ###
