"""empty message

Revision ID: 6d6aac73b2dc
Revises: 5beeef835e22
Create Date: 2019-11-30 12:53:29.636700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6aac73b2dc'
down_revision = '5beeef835e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('rank_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'rank_points')
    # ### end Alembic commands ###
