"""empty message

Revision ID: 6fc26fc454ae
Revises: 80303bcabc81
Create Date: 2019-12-03 10:20:14.290927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc26fc454ae'
down_revision = '80303bcabc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_confirmed', sa.Boolean(), nullable=False))
    op.drop_column('results', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('results', 'result_confirmed')
    # ### end Alembic commands ###
