"""empty message

Revision ID: 80303bcabc81
Revises: 5beeef835e22
Create Date: 2019-12-02 11:04:32.784975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80303bcabc81'
down_revision = '5beeef835e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['organiser_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('players', sa.Column('rank_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'rank_points')
    op.drop_table('messages')
    # ### end Alembic commands ###
