"""empty message

Revision ID: 834f110b58ca
Revises: cd68d64ae9e2
Create Date: 2019-11-28 17:49:20.611807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834f110b58ca'
down_revision = 'cd68d64ae9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('profile_image', sa.LargeBinary(), nullable=True))
    op.create_foreign_key(None, 'results', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('players', 'profile_image')
    # ### end Alembic commands ###
