"""empty message

Revision ID: c1f63bad312f
Revises: 3efaeab010a9
Create Date: 2019-12-01 14:12:53.221112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f63bad312f'
down_revision = '3efaeab010a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_opponent_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'players', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'players', ['sender_id'], ['id'])
    op.drop_column('messages', 'opponent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('opponent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_opponent_id_fkey', 'messages', 'players', ['opponent_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
